import type { Product } from './types';

export const CATEGORIES = ["All", "Games", "Lingerie", "Ambiance", "Novelties"];

// NOTE: Products now use real ASINs (Amazon Standard Identification Number).
// Affiliate links will be constructed dynamically based on user's region.
// Replace 'yourtag-20' in utils/amazon.ts with your actual Amazon affiliate tag.
export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "The Adventure Challenge: Couples Edition",
    description: "50 scratch-off adventures to bring spontaneity and romance back into your relationship.",
    imageUrl: "https://m.media-amazon.com/images/I/71N-W1A2-rL._AC_SL1500_.jpg",
    asin: "1952783002",
    category: "Games",
  },
  {
    id: 2,
    name: "Luxury Floral Lace Bodysuit",
    description: "An exquisite floral lace teddy that combines elegance with jaw-dropping allure.",
    imageUrl: "https://m.media-amazon.com/images/I/71R2p-MZLDL._AC_UX679_.jpg",
    asin: "B07X5L3D4W",
    category: "Lingerie",
  },
  {
    id: 3,
    name: "Kama Sutra Aromatics Massage Oil",
    description: "A warming, sensual blend of natural oils for a deeply relaxing and intimate massage.",
    imageUrl: "https://m.media-amazon.com/images/I/61y8B3x7qRL._AC_SL1500_.jpg",
    asin: "B0006L142A",
    category: "Ambiance",
  },
  {
    id: 4,
    name: "We-Vibe Nova 2",
    description: "App-controlled couples vibrator, perfect for partnered play and long-distance relationships.",
    imageUrl: "https://m.media-amazon.com/images/I/61q3-Jd-mSL._AC_SL1500_.jpg",
    asin: "B09G2S7Y2P",
    category: "Novelties",
  },
  {
    id: 5,
    name: "OUR MOMENTS Couples: Conversation Starters",
    description: "100 thought-provoking conversation starters for couples to connect on a deeper level.",
    imageUrl: "https://m.media-amazon.com/images/I/81D30k41DVL._AC_SL1500_.jpg",
    asin: "B078RDJ1M9",
    category: "Games",
  },
  {
    id: 6,
    name: "Womanizer Premium 2",
    description: "Revolutionary pleasure air technology for intense, touchless stimulation. Waterproof and whisper quiet.",
    imageUrl: "https://m.media-amazon.com/images/I/51b34L1S-KL._AC_SL1500_.jpg",
    asin: "B09B2Q4W56",
    category: "Novelties",
  },
  {
    id: 7,
    name: "Paddywax Apothecary Scented Candle",
    description: "Set a romantic mood with this Tobacco & Patchouli scented soy candle in a vintage apothecary jar.",
    imageUrl: "https://m.media-amazon.com/images/I/71KzR4R-y+L._AC_SL1500_.jpg",
    asin: "B01N0R42D7",
    category: "Ambiance",
  },
  {
    id: 8,
    name: "Avidlove Satin Lace Kimono Robe",
    description: "A silky, comfortable, and alluring robe with lace trim, perfect for evenings in.",
    imageUrl: "https://m.media-amazon.com/images/I/71OQ1e-J6SL._AC_UX569_.jpg",
    asin: "B078B3CT9X",
    category: "Lingerie",
  },
  {
    id: 9,
    name: "LELO Sona Cruise 2",
    description: "A sonic clitoral massager that offers a different kind of orgasm through sonic waves and pulses.",
    imageUrl: "https://m.media-amazon.com/images/I/61gXw8t0BRL._AC_SL1500_.jpg",
    asin: "B07V35KGM2",
    category: "Novelties",
  },
  {
    id: 10,
    name: "Crave Vesper Vibrator Necklace",
    description: "A stunning piece of jewelry that doubles as a powerful, discreet vibrator. USB rechargeable.",
    imageUrl: "https://m.media-amazon.com/images/I/61pW+B3XJHL._AC_SL1500_.jpg",
    asin: "B075R8G211",
    category: "Novelties",
  },
  {
    id: 11,
    name: "Talk, Flirt, Dare: Couples Game",
    description: "Three game levels to choose from, allowing you to control the intimacy level of your night.",
    imageUrl: "https://m.media-amazon.com/images/I/81h9aYnCiEL._AC_SL1500_.jpg",
    asin: "B07GP2853Z",
    category: "Games",
  },
  {
    id: 12,
    name: "Honeydew Sensual Massage Oil for Couples",
    description: "100% natural blend of Jojoba and Almond oil with Vitamin E. Hypoallergenic and stain-free.",
    imageUrl: "https://m.media-amazon.com/images/I/716a5+s-Y2L._AC_SL1500_.jpg",
    asin: "B01B1124G2",
    category: "Ambiance",
  },
  {
    id: 13,
    name: "RSLOVE Lace Teddy Lingerie",
    description: "One piece deep V-neck lace bodysuit with a stretch strap and G-string.",
    imageUrl: "https://m.media-amazon.com/images/I/71lq18f-74L._AC_UY879_.jpg",
    asin: "B08927CR5B",
    category: "Lingerie",
  },
  {
    id: 14,
    name: "Anjou Scented Candles Gift Set",
    description: "A gift set of 4 natural soy wax candles with scents like Lavender, Freesia, and French Vanilla.",
    imageUrl: "https://m.media-amazon.com/images/I/81xUe5-0yVS._AC_SL1500_.jpg",
    asin: "B0936L868C",
    category: "Ambiance",
  },
  {
    id: 15,
    name: "Lovehoney Power Play Couples Vibrator",
    description: "A flexible C-shaped vibrator designed to be worn during intercourse for mutual pleasure.",
    imageUrl: "https://m.media-amazon.com/images/I/61mQ-6m0kCL._AC_SL1500_.jpg",
    asin: "B09KMRX6FK",
    category: "Novelties",
  },
  {
    id: 16,
    name: "{THE AND} Couples Edition",
    description: "A deck of 199 questions to get to know your partner on a more meaningful level.",
    imageUrl: "https://m.media-amazon.com/images/I/71w-Xmn7lJL._AC_SL1500_.jpg",
    asin: "B084T6116S",
    category: "Games",
  },
  {
    id: 17,
    name: "Magic Wand Rechargeable",
    description: "The legendary powerful vibrator, now cordless and rechargeable with 4 intensity levels.",
    imageUrl: "https://m.media-amazon.com/images/I/61O+2+ODaDL._AC_SL1500_.jpg",
    asin: "B01D42S64E",
    category: "Novelties",
  },
  {
    id: 18,
    name: "YSL Black Opium Eau de Parfum",
    description: "A captivating floral gourmand scent, twisted with an overdose of black coffee, for a shot of adrenaline.",
    imageUrl: "https://m.media-amazon.com/images/I/610tVoLzDmL._AC_SL1500_.jpg",
    asin: "B00M0T4B8K",
    category: "Ambiance",
  },
  {
    id: 19,
    name: "I DEW CARE Sheet Mask Set",
    description: "A set of 14 Korean skincare face masks to relax and rejuvenate together.",
    imageUrl: "https://m.media-amazon.com/images/I/713YfR5aNOL._AC_SL1500_.jpg",
    asin: "B084Z1B8B3",
    category: "Ambiance",
  },
  {
    id: 20,
    name: "AdoreMe Adelia Unlined Bodysuit",
    description: "Show off your curves in this gorgeous floral lace and mesh bodysuit with daring cutouts.",
    imageUrl: "https://m.media-amazon.com/images/I/81Q-yUoN8iL._AC_UY879_.jpg",
    asin: "B09W2J3W7C",
    category: "Lingerie",
  },
];